---
title: "LA County Coronavirus Cases"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(readr)
library(ggplot2)
library(plotly)

# load data in 'global' chunk so it can be shared by all users of the dashboard
total_merge <- read_rds(path = "data/merged/total-merged.rds")
age_merge <- read_rds(path = "data/merged/age-merged.rds")
death_merge <- read_rds(path = "data/merged/death-merged.rds")
hospitalization_merge <- read_rds(path = "data/merged/hospitalization-merged.rds")
community_merge <- read_rds(path = "data/merged/community-merged.rds")
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("community", 
            h4("Choose Community"), 
            choices = community_merge$locations, 
            selected = "Alhambra",
            multiple = T)
```

**Please use the community selector above to view your communities of interest in the third graph.**

The LA County Public Health office posts the counts of coronavirus cases in both total and by community each day. The goal of this dashboard is to capture their data on a daily basis so that we can visualize a daily trend in total and across communities.

Last Updated: `r max(total_merge$case_date)`

Data Source: [LA County Public Health Dept](http://www.publichealth.lacounty.gov/media/Coronavirus/locations.htm)

Code: [Github](https://github.com/phdjsep/la-county-coronavirus-cases)

Made by: [Sep Dadsetan](https://www.linkedin.com/in/sepdadsetan)

Row
-----------------------------------------------------------------------

### Total Cases

```{r}
# Total Case Value Box
valueBox(max(total_merge$total_cases), 
         caption = "Total Cases", 
         icon = 'fa-medkit',
         color = 'warning')
```

### Total Hospitalized

```{r}
# Total Hospitalized Value Box
valueBox(max(hospitalization_merge$total_cases), 
         caption = "Total Hospitalized", 
         icon = 'fa-hospital',
         color = 'warning')
```

### Total Deaths

```{r}
# extract latest death count
death_count <- death_merge %>% 
  filter(locations == "Deaths") %>% 
  pull(total_cases) %>% 
  max()

# Total Death Value Box
valueBox(death_count, 
         caption = "Total Deaths", 
         icon = 'fa-heart',
         color = 'danger')
```

Row
-----------------------------------------------------------------------

### Laboratory Confirmed Cases of Coronavirus by Location

```{r}
p <- ggplot(total_merge, aes(x = case_date, y = total_cases, group = locations, color = locations)) + 
            geom_line() + 
            geom_point()
ggplotly(p, tooltip = c("total_cases", "case_date")) %>% 
   layout(legend = list(x = 0, y = 1, bgcolor = "rgba(0,0,0,0)"))
```

### Laboratory Confirmed Cases of Coronavirus by Age Group (median age 47)

```{r}
p <- ggplot(age_merge, aes(x = case_date, y = total_cases, group = locations, color = locations)) +
    geom_line() +
    geom_point()
ggplotly(p, tooltip = c("total_cases", "case_date")) %>% 
   layout(legend = list(x = 0, y = 1, bgcolor = "rgba(0,0,0,0)"))
```

Row
-----------------------------------------------------------------------

### Laboratory Confirmed Cases of Coronavirus by Community

```{r}
renderPlotly({
p <- ggplot(filter(community_merge, locations %in% input$community), aes(x = case_date, y = total_cases, group = locations, color = locations)) +
            geom_line() +
            geom_point()
ggplotly(p) %>% 
   layout(legend = list(x = 0, y = 1, bgcolor = "rgba(0,0,0,0)"))
})
```